services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    attach: false
    restart: unless-stopped

  backend:
    build: ./application
    environment:
      NODE_ENV: production
      PORT: "8080"
      MONGO_URI: "mongodb://mongo:27017/netviz"
    env_file:
      - path: ./application/.env
        required: true

    depends_on:
      - mongo
    ports:
      - "8080:8080"
    restart: unless-stopped
