services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    restart: unless-stopped

  backend:
    build: ./application
    environment:
      NODE_ENV: production
      PORT: "8080"
      MONGO_URI: "mongodb://mongo:27017/netviz"
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    restart: unless-stopped
